// Building definitions: static data for every buildable structure.
// Fields not relevant to a building are 0, null, false or {}.
//
// Field reference:
//   cost          resources needed to build ({ wood?, metal? })
//   category      build-menu category id (see CATEGORIES)
//   produces      per-day resource output ({ food?, water?, energy? })
//   consumes      per-day fuel needed to run ({ water?, wood? }); without it
//                 the building stalls (no production, no consumption)
//   jobs          worker slots; output scales with assigned workers
//   houses        survivor housing slots
//   requiresEnergy  energy drained per day from the grid; powered while energy > 0
//   energyDayOnly produces energy only during the day phase (solar)
//   capBonus      extra storage capacity per resource ({ energy?, water?, ... })
//   extracts      map node type the building depletes ('forest'|'ruins'|'ore')
//   extractRate   per-day amount taken from the node
//   plants        map node type the building regrows (forester)
//   researchRate  per-day research points produced
//   requiresTech  tech id that must be researched before building
//   isWall        blocks zombie pathing until destroyed
//   isTower       shoots zombies automatically
//   isTrap        damages zombies walking over it
//   trapDamage    damage dealt per trigger (traps)
//
// Optional field (not part of the required schema):
//   proximity     site-efficiency rule { tile: 'water'|'forest'|'wildlife',
//                 range, poor }: output is full when such a tile lies within
//                 `range` of the footprint, scaled by `poor` otherwise (well,
//                 hunt, fish, ranch)
//   isRoad        road tile: supports drag-placement in a row like walls and
//                 grants the logistics aura (see sim/modifiers.js)
//   modelScaleMul visual-only scale multiplier applied after the footprint
//                 normalization (default 1): gives a building extra presence
//                 (hq), letting it overhang its footprint a little
//   modelWidthFrac visual-only horizontal extent, as a fraction of the
//                 footprint span (default 0.95): thin structures (road)

export const BUILDING_DEFS = {
  hq: {
    id: 'hq',
    name: '본부 (Refuge)',
    desc: '정착지의 심장부입니다. 밤에도 에너지를 생산하고 4명의 생존자를 수용합니다. 무너지면 게임 오버.',
    cost: {},
    category: 'infrastrutture',
    w: 3,
    h: 3,
    hp: 1000,
    produces: { energy: 4 },
    consumes: {},
    jobs: 0,
    houses: 4,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'hq',
    modelScaleMul: 0.5,
  },
  tent: {
    id: 'tent',
    name: '천막 (Tent)',
    desc: '2명의 생존자를 수용하는 임시 거처입니다.',
    cost: { wood: 10 },
    category: 'abitazioni',
    w: 1,
    h: 1,
    hp: 100,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 2,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'tent',
  },
  shack: {
    id: 'shack',
    name: '판잣집 (Shack)',
    desc: '3명의 생존자를 수용하는 골판지 판잣집입니다. 싸지만 약합니다.',
    cost: { wood: 15 },
    category: 'abitazioni',
    w: 1,
    h: 1,
    hp: 80,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 3,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'shack',
  },
  house: {
    id: 'house',
    name: '주택 (House)',
    desc: '4명의 생존자를 수용하는 튼튼한 주택입니다.',
    cost: { wood: 25, metal: 10 },
    category: 'abitazioni',
    w: 2,
    h: 2,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 4,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'house',
  },
  farm: {
    id: 'farm',
    name: '농장 (Farm)',
    desc: '매일 식량을 생산하지만 물을 소비합니다. 작업자 2명이 필요합니다.',
    cost: { wood: 30 },
    category: 'sostentamento',
    w: 2,
    h: 2,
    hp: 150,
    produces: { food: 8 },
    consumes: { water: 3 },
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'farm',
  },
  garden: {
    id: 'garden',
    name: '텃밭 (Garden)',
    desc: '물을 조금 들여 식량을 생산하는 작은 텃밭입니다. 작업자 1명이 필요합니다.',
    cost: { wood: 15 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 100,
    produces: { food: 4 },
    consumes: { water: 2 },
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'garden',
  },
  greenhouse: {
    id: 'greenhouse',
    name: '온실 (Greenhouse)',
    desc: '보온된 고수확 온실입니다. 에너지, 물, 작업자 2명이 필요합니다.',
    cost: { wood: 40, metal: 20 },
    category: 'sostentamento',
    w: 2,
    h: 2,
    hp: 180,
    produces: { food: 14 },
    consumes: { water: 5 },
    jobs: 2,
    houses: 0,
    requiresEnergy: 1,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'greenhouse',
  },
  rain: {
    id: 'rain',
    name: '빗물 수집기 (Rain Collector)',
    desc: '귀중한 빗물을 모읍니다. 비가 올 때 훨씬 많이, 폭염에는 아주 조금만 모읍니다.',
    cost: { wood: 15 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 80,
    produces: { water: 4 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'rain-collector',
  },
  well: {
    id: 'well',
    name: '우물 (Well)',
    desc: '작업자 없이 자동으로 지하수를 끌어올립니다. 물 근처에서 수량이 더 많습니다.',
    cost: { wood: 20, metal: 10 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 100,
    produces: { water: 8 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'well',
    proximity: { tile: 'water', range: 3, poor: 0.4 },
  },
  cistern: {
    id: 'cistern',
    name: '물탱크 (Cistern)',
    desc: '물을 여과하고 물 저장 용량을 늘려주는 물탱크입니다.',
    cost: { metal: 25 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 150,
    produces: { water: 2 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: { water: 60 },
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'cistern',
  },
  hunt: {
    id: 'hunt',
    name: '사냥 오두막 (Hunting Cabin)',
    desc: '주변 들판에서 사냥을 합니다. 숲 근처에서 수량이 더 좋습니다. 작업자 1명이 필요합니다.',
    cost: { wood: 20 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 100,
    produces: { food: 6 },
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'hunt',
    proximity: { tile: 'forest', range: 3, poor: 0.5 },
  },
  fish: {
    id: 'fish',
    name: '낚시 오두막 (Fishing Cabin)',
    desc: '주변에서 물고기를 잡습니다. 물 근처에서 수량이 더 좋습니다. 작업자 1명이 필요합니다.',
    cost: { wood: 15 },
    category: 'sostentamento',
    w: 1,
    h: 1,
    hp: 100,
    produces: { food: 5 },
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'fish',
    proximity: { tile: 'water', range: 2, poor: 0.5 },
  },
  ranch: {
    id: 'ranch',
    name: '목장 (Ranch)',
    desc: '근처 야생 무리에서 잡은 동물을 기릅니다. 무리 근처에서 수량이 더 좋습니다. 직원이 배치되면 가축이 농장과 운반 작업에 힘을 보탭니다. 작업자 2명이 필요합니다.',
    cost: { wood: 40 },
    category: 'sostentamento',
    w: 2,
    h: 2,
    hp: 150,
    produces: { food: 10 },
    consumes: {},
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'ranch',
    proximity: { tile: 'wildlife', range: 3, poor: 0.5 },
  },
  lumber: {
    id: 'lumber',
    name: '벌목장 (Lumberjack)',
    desc: '고갈될 때까지 근처 숲의 나무를 베어냅니다. 작업자 2명이 필요합니다.',
    cost: { wood: 15 },
    category: 'risorse',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: 'forest',
    extractRate: 10,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'lumber',
  },
  forester: {
    id: 'forester',
    name: '식림장 (Forester)',
    desc: '고갈된 숲에 새 나무를 심어 다시 자라게 합니다. 작업자 1명이 필요합니다.',
    cost: { wood: 20 },
    category: 'risorse',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: 'forest',
    researchRate: 0,
    requiresTech: 'forestry',
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'forester',
  },
  scavenger: {
    id: 'scavenger',
    name: '고철 수거장 (Scavenger)',
    desc: '폐허에서 고철을 회수합니다. 작업자 2명이 필요합니다.',
    cost: { wood: 25 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 150,
    produces: {},
    consumes: {},
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: 'ruins',
    extractRate: 6,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'scrapyard',
  },
  mine: {
    id: 'mine',
    name: '광산 (Mine)',
    desc: '광맥에서 금속을 채굴합니다. 작업자 3명이 필요합니다.',
    cost: { wood: 30, metal: 20 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 250,
    produces: {},
    consumes: {},
    jobs: 3,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: 'ore',
    extractRate: 8,
    plants: null,
    researchRate: 0,
    requiresTech: 'mining',
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'mine',
  },
  smelter: {
    id: 'smelter',
    name: '제련소 (Smelter)',
    desc: '고철과 목재를 녹여 쓸 수 있는 금속으로 만듭니다. 작업자 2명이 필요합니다.',
    cost: { wood: 30, metal: 30 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 250,
    produces: { metal: 3 },
    consumes: { wood: 2 },
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'smelter',
  },
  distillery: {
    id: 'distillery',
    name: '정유소 (Distillery)',
    desc: '목재를 증류하여 정착지의 차량용 연료를 만듭니다. 목재가 없으면 작동을 멈춥니다. 작업자 1명이 필요합니다.',
    cost: { wood: 30, metal: 15 },
    category: 'risorse',
    w: 1,
    h: 1,
    hp: 120,
    produces: { fuel: 4 },
    consumes: { wood: 3 },
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'distillery',
  },
  garage: {
    id: 'garage',
    name: '차고 (Garage)',
    desc: '정착지의 차량이 도로를 달리도록 관리합니다. 직원이 배치되면 채굴량이 50% 증가합니다. 효과는 중첩되지 않습니다. 연료를 소모하며 작업자 1명이 필요합니다.',
    cost: { wood: 40, metal: 30 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 200,
    produces: {},
    consumes: { fuel: 3 },
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'garage',
  },
  warehouse: {
    id: 'warehouse',
    name: '창고 (Warehouse)',
    desc: '식량·목재·금속 저장 용량을 늘려주는 넓은 창고입니다.',
    cost: { wood: 40 },
    category: 'risorse',
    w: 2,
    h: 2,
    hp: 300,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: { food: 100, wood: 100, metal: 100 },
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'warehouse',
  },
  lab: {
    id: 'lab',
    name: '연구소 (Laboratory)',
    desc: '옛 세계의 유물을 연구하여 연구 포인트를 생산합니다. 작업자 2명이 필요합니다.',
    cost: { wood: 30, metal: 25 },
    category: 'infrastrutture',
    w: 2,
    h: 2,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 2,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 4,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'lab',
  },
  clinic: {
    id: 'clinic',
    name: '진료소 (Clinic)',
    desc: '생존자를 돌봅니다. 작업자가 1명이라도 있으면 배고픔과 갈증이 더 천천히 증가합니다.',
    cost: { wood: 30, metal: 15 },
    category: 'infrastrutture',
    w: 2,
    h: 2,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'clinic',
  },
  radio: {
    id: 'radio',
    name: '비상 무선 (Emergency Radio)',
    desc: '사막으로 구조 요청을 방송합니다. 직원이 배치되면 매일 새벽마다 생존자 1명이 추가로 도착합니다. 작업자 1명이 필요합니다.',
    cost: { wood: 30, metal: 20 },
    category: 'infrastrutture',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'radio',
  },
  road: {
    id: 'road',
    name: '도로 (Road)',
    desc: '포장된 도로입니다. 자원으로의 운반이 빨라지고, 도로 하나당 채굴량이 2%씩 (최대 40%) 증가합니다. 벽과 마찬가지로 드래그하여 연속으로 배치할 수 있습니다.',
    cost: { wood: 2 },
    category: 'infrastrutture',
    w: 1,
    h: 1,
    hp: 50,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'road',
    isRoad: true,
    modelWidthFrac: 0.25,
  },
  solar: {
    id: 'solar',
    name: '태양광 패널 (Solar Panel)',
    desc: '에너지를 생산하지만 낮에만 작동합니다.',
    cost: { metal: 35 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 80,
    produces: { energy: 5 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: true,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'solar-panel',
  },
  'solar-plant': {
    id: 'solar-plant',
    name: '태양광 발전소 (Solar Plant)',
    desc: '태양광 패널이 모인 발전소입니다. 풍부한 에너지를 생산하지만 낮에만 가능합니다.',
    cost: { metal: 80 },
    category: 'energia',
    w: 2,
    h: 2,
    hp: 150,
    produces: { energy: 14 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: true,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: 'solar2',
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'solar-plant',
  },
  wind: {
    id: 'wind',
    name: '풍력 터빈 (Wind Turbine)',
    desc: '낮과 밤 모두 에너지를 생산합니다. 비가 오거나 폭풍일 때 더 많은 에너지를 냅니다.',
    cost: { metal: 45 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 120,
    produces: { energy: 3 },
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'wind-turbine',
  },
  generator: {
    id: 'generator',
    name: '발전기 (Generator)',
    desc: '목재를 태워 밤에도 에너지를 만듭니다. 작업자 1명이 필요합니다.',
    cost: { metal: 40 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 120,
    produces: { energy: 6 },
    consumes: { wood: 3 },
    jobs: 1,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'generator',
  },
  battery: {
    id: 'battery',
    name: '축전지 (Battery)',
    desc: '여분의 에너지를 저장하고 전력망의 용량을 늘려줍니다.',
    cost: { metal: 35 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 100,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: { energy: 50 },
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: 'batteries',
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'battery',
  },
  motor: {
    id: 'motor',
    name: '전동 모터 (Electric Motor)',
    desc: '채굴 작업을 도와주는 모터입니다. 전력망이 충전되어 있으면 채굴량이 25% 증가합니다. 효과는 중첩되지 않습니다.',
    cost: { metal: 30 },
    category: 'energia',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 2,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'motor',
  },
  palisade: {
    id: 'palisade',
    name: '목책 (Palisade)',
    desc: '나무로 만든 목책입니다. 싸고 빠르게 쌓을 수 있지만 내구도가 약합니다.',
    cost: { wood: 8 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: true,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'palisade',
  },
  'scrap-wall': {
    id: 'scrap-wall',
    name: '고철 벽 (Scrap Wall)',
    desc: '용접된 골판지 벽입니다. 적당한 비용에 준수한 내구도를 자랑합니다.',
    cost: { metal: 15 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 450,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: true,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'scrap-wall',
  },
  'brick-wall': {
    id: 'brick-wall',
    name: '벽돌 담장 (Brick Wall)',
    desc: '좀비 무리의 공격을 오래 견디는 견고한 벽돌 담장입니다.',
    cost: { wood: 20 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 800,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: true,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'brick-wall',
  },
  'concrete-wall': {
    id: 'concrete-wall',
    name: '콘크리트 벽 (Concrete Wall)',
    desc: '최고의 보루입니다. 좀비의 공격에 거의 무적입니다.',
    cost: { metal: 30 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 1400,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: 'concrete',
    isWall: true,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'concrete-wall',
  },
  tower: {
    id: 'tower',
    name: '망루 (Watch Tower)',
    desc: '사정거리 안의 좀비를 자동으로 사격합니다. 에너지와 작업자 1명이 필요합니다.',
    cost: { wood: 20, metal: 30 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 200,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 1,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: true,
    isTrap: false,
    trapDamage: 0,
    damage: 10,
    range: 6,
    fireRate: 1,
    model: 'tower',
  },
  sniper: {
    id: 'sniper',
    name: '저격포탑 (Sniper Turret)',
    desc: '원거리 정밀 포탑입니다. 많은 에너지와 작업자 1명이 필요합니다.',
    cost: { metal: 35 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 250,
    produces: {},
    consumes: {},
    jobs: 1,
    houses: 0,
    requiresEnergy: 2,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: 'ballistics',
    isWall: false,
    isTower: true,
    isTrap: false,
    trapDamage: 0,
    damage: 22,
    range: 8,
    fireRate: 0.8,
    model: 'sniper-tower',
  },
  spotlight: {
    id: 'spotlight',
    name: '야간 조명등 (Field Spotlight)',
    desc: '전력망으로 작동하는 조명등입니다. 전력망이 충전되어 있는 동안 정착지의 타워가 주는 피해가 20% 증가합니다. 효과는 중첩되지 않습니다.',
    cost: { wood: 25, metal: 15 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 120,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 2,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'spotlight',
  },
  streetlamp: {
    id: 'streetlamp',
    name: '가로등 (Street Lamp)',
    desc: '정착지 거리를 밝혀줍니다. 전력망이 충전되어 있는 동안 수비대와 민병대의 공격력이 25% 증가합니다. 효과는 중첩되지 않습니다.',
    cost: { wood: 10, metal: 5 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 80,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 1,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: false,
    trapDamage: 0,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'streetlamp',
  },
  trap: {
    id: 'trap',
    name: '함정 지대 (Trap Field)',
    desc: '지나가는 좀비에게 피해를 주는 함정 지대입니다.',
    cost: { wood: 10 },
    category: 'difesa',
    w: 1,
    h: 1,
    hp: 100,
    produces: {},
    consumes: {},
    jobs: 0,
    houses: 0,
    requiresEnergy: 0,
    energyDayOnly: false,
    capBonus: {},
    extracts: null,
    extractRate: 0,
    plants: null,
    researchRate: 0,
    requiresTech: null,
    isWall: false,
    isTower: false,
    isTrap: true,
    trapDamage: 6,
    damage: 0,
    range: 0,
    fireRate: 0,
    model: 'trap',
  },
};

/** Build-menu categories, in display order. */
export const CATEGORIES = [
  { id: 'abitazioni', name: '주거', icon: '🏠' },
  { id: 'sostentamento', name: '식량·물', icon: '🥫' },
  { id: 'risorse', name: '자원', icon: '🪵' },
  { id: 'energia', name: '에너지', icon: '⚡' },
  { id: 'difesa', name: '방어', icon: '🛡️' },
  { id: 'infrastrutture', name: '기반시설', icon: '🏛️' },
];

/** Order in which buildings appear in the build menu, grouped by category. */
export const BUILD_MENU_ORDER = [
  // Abitazioni (주거)
  'tent',
  'shack',
  'house',
  // Sostentamento (식량·물)
  'farm',
  'garden',
  'greenhouse',
  'rain',
  'well',
  'cistern',
  'hunt',
  'fish',
  'ranch',
  // Risorse (자원)
  'lumber',
  'forester',
  'scavenger',
  'mine',
  'smelter',
  'distillery',
  'garage',
  'warehouse',
  // Energia (에너지)
  'solar',
  'solar-plant',
  'wind',
  'generator',
  'motor',
  'battery',
  // Difesa (방어)
  'palisade',
  'scrap-wall',
  'brick-wall',
  'concrete-wall',
  'tower',
  'sniper',
  'spotlight',
  'streetlamp',
  'trap',
  // Infrastrutture (기반시설)
  'lab',
  'clinic',
  'radio',
  'road',
];

/**
 * Returns the definition for a building id.
 * @param {string} id
 * @returns {object | undefined}
 */
export function getDef(id) {
  return BUILDING_DEFS[id];
}
